config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tribe_members, only: [:new, :create, :index]
  root 'tribe_members#index'
  get "tribe_members/show_stats", to: "tribe_members#show_stats"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stat.rb
class Stat < ApplicationRecord
  serialize :older, Hash
  serialize :average, Array

  def self.prepare_hash
    hash = TribeMember.all.group_by { |tm| tm.birthdate.year }
    hash_count = {}
    hash.each do |key, value|
      hash_count[key] = value.count
    end
    hash_count
  end
end

app/models/tribe_member.rb
class TribeMember < ApplicationRecord
  attr_accessor :ancestor_name, :ancestor_surname

  belongs_to :ancestor, class_name: "TribeMember", foreign_key: :ancestor, optional: true

  scope :by_name, -> (val) {
    TribeMember.where(name: val)
  }

  scope :by_surname, -> (val) {
    TribeMember.where(surname: val)
  }

  scope :by_birthdate, -> (val) {
    TribeMember.select{|tm| tm.birthdate == val.to_date}
  }

  scope :get_ancestor, -> (val) {
    TribeMember.find(val)
  }

  def self.set_location_array
    locations = []
    TribeMember.all.each do |tm|
      next if tm.latitude.nil? || tm.longitude.nil?
      a = [tm.latitude.to_f, tm.longitude.to_f]
      locations << a
    end
    locations
  end

  def self.search(params)
    if params[:name].present?
      search_result = TribeMember.by_name(params[:name])

    elsif params[:surname].present?
      search_result = TribeMember.by_surname(params[:surname])

    elsif params[:member_birthdate].present?
      if params[:member_birthdate]["birthdate(2i)"].to_i < 10
        params[:member_birthdate]["birthdate(2i)"] = "0" + params[:member_birthdate]["birthdate(2i)"]
      end
      if params[:member_birthdate]["birthdate(3i)"].to_i < 10
       params[:member_birthdate]["birthdate(3i)"] = "0" + params[:member_birthdate]["birthdate(3i)"]
      end
      birthdate = params[:member_birthdate]["birthdate(1i)"] + "-" + params[:member_birthdate]["birthdate(2i)"] + "-" + params[:member_birthdate]["birthdate(3i)"]
      search_result = TribeMember.by_birthdate(birthdate)

    elsif params[:ancestor_name].present? && params[:ancestor_surname].present?
      ancestor = TribeMember.where(name: params[:ancestor_name], surname: params[:ancestor_surname]).first
      search_result = TribeMember.where("ancestor = ?", ancestor.id)
    end

    if search_result == []
      search_result = "no result"
    end

    search_result
  end

  def self.build_geojson
    geojson = { "type" => "FeatureCollection", "features" => []}

    TribeMember.all.each do |tm|
      hash = {
        type: 'Feature',
        geometry: {
          type: 'Point',
          coordinates: [tm.latitude.to_f, tm.longitude.to_f]
        },
        properties: {
        title: tm.id
        }
      }

      geojson["features"] << hash
    end

    geojson_json = geojson.to_json
    File.open("public/geo.geojson","w") do |f|
      f.write(geojson_json)
    end
    geojson
  end

  def self.add_to_geojson(tribe_member)
    data_hash = JSON.parse(File.read('public/geo.geojson'))
    hash = {"type"=>"Feature", "geometry"=>{"type"=>"Point", "coordinates"=>[tribe_member.latitude, tribe_member.longitude]}, "properties"=>{"title"=>tribe_member.id}}
    data_hash["features"] << hash

    geo_to_save = data_hash.to_json

    File.open("public/geo.geojson","w") do |f|
      f.write(geo_to_save)
    end
  end

  def self.data_parse
    average_age = Stat.last.average.sum / Stat.last.average.count
    oldest_member = TribeMember.find(Stat.last.older[:id])
    data_to_show = {average: average_age, count: Stat.last.total_member, oldest_member: oldest_member, age_oldest_member: Stat.last.older[:age]}
  end

  def self.add_to_stats(tribe_member)
    stat = Stat.last
    age_year = ((Time.zone.now - tribe_member.birthdate.to_time) / 1.year.seconds).floor
    stat.average << age_year
    age_time = Time.zone.now - tribe_member.birthdate.to_time
    if stat.older[:age_time] < age_time
      stat.older[:age_time] = age_time
      stat.older[:age] = age_year
      stat.older[:id] = tribe_member.id
    end

    stat.total_member = stat.total_member + 1
    stat.save

  end

  def self.generate_stats
    puts "start"
    count = 0
    average = []
    older = {age: 0, age_time: 0, id: nil}
    TribeMember.all.each do |tm|
      puts "#{tm.id}"
      count += 1

      age_year = ((Time.zone.now - tm.birthdate.to_time) / 1.year.seconds).floor
      age_time = Time.zone.now - tm.birthdate.to_time

      average << age_year
      if older[:age_time] < age_time
        older[:age] = age_year
        older[:age_time] = age_time
        older[:id] = tm.id
      end
      puts "older: #{older}"
    end

    puts "count: #{count}"
    stat = Stat.new(total_member: count, older: older, average: average)
    stat.save

  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tribe_members.rb
class TribeMembersController < ApplicationController

  def index
  end

  def new
  end

  def create
  end

end

app/controllers/tribe_members_controller.rb
class TribeMembersController < ApplicationController
  def index
    if params[:name].present? || params[:surname] || params[:member_birthdate] || params[:ancestor_name]
      @search_result = TribeMember.search(params)
    else
      @tribe_m = TribeMember.all.paginate(:page => params[:page], :per_page => 15)
    end
  end

  def new
    @tribe_member = TribeMember.new
  end


  def create
    ancestor = TribeMember.where(name: params[:tribe_member][:ancestor_name], surname: params[:tribe_member][:ancestor_surname]).first
    @tribe_member = TribeMember.new(tribe_member_params)
    @tribe_member.ancestor = ancestor
    if @tribe_member.save
      TribeMember.add_to_stats(@tribe_member)
      TribeMember.add_to_geojson(@tribe_member)
      redirect_to tribe_members_path
    else
      render :new
    end
  end

  def show_stats
    @stats = TribeMember.data_parse
    @data_graph = Stat.prepare_hash
  end

  private

  def tribe_member_params
    params.require(:tribe_member).permit(:name, :surname, :birthdate, :latitude, :longitude)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TribeMembers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css" />
    <link rel="stylesheet" href="https://cdn.rawgit.com/mapbox/supercluster/v4.0.1/demo/cluster.css" />
    <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet-src.js"></script>
    <script src="https://unpkg.com/supercluster@4.0.1/dist/supercluster.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>


<!--     <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css" integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ==" crossorigin="" />
    <link rel="stylesheet" href="https://cdn.rawgit.com/mapbox/supercluster/v4.0.1/demo/cluster.css" />
    <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet-src.js" integrity="sha512-IkGU/uDhB9u9F8k+2OsA6XXoowIhOuQL1NTgNZHY1nkURnqEGlDZq3GsfmdJdKFe1k1zOc6YU2K7qY+hF9AodA==" crossorigin=""></script>
    <script src="https://unpkg.com/supercluster@4.0.1/dist/supercluster.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script> -->
<!--     <link rel="stylesheet" href="https://unpkg.com/leaflet@1.4.0/dist/leaflet.css" />
    <link rel="stylesheet" href="https://cdn.rawgit.com/mapbox/supercluster/v4.0.1/demo/cluster.css" />

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://unpkg.com/leaflet@1.4.0/dist/leaflet.js"></script>
    <script src="https://unpkg.com/supercluster@4.0.1/dist/supercluster.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script> -->


 <!--    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-ajax/2.1.0/leaflet.ajax.min.js"></script>
    <script src="https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/leaflet.markercluster.js"></script> -->

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tribe_members/index.html.erb
<div class="banner">
  <h1>Tribe Member Around The World !</h1>
</div>
<br>
<div class="container">
  <div class="row">
    <div class="col-6">
      <div class="card">
        <h3>Search</h3>
        <p>search by name</p>
          <%= form_tag(tribe_members_path, method: :get) do %>
            <%= text_field_tag(:name, params[:name], required: true, class: "search-form")%>
            <%= submit_tag "Search", id: "search_by_name", class: "btn btn-outline-warning btn-sm search-btn-margin"%>
          <% end %>

        <p>search by surname</p>
          <%= form_tag(tribe_members_path, method: :get) do %>
            <%= text_field_tag(:surname, params[:surname], required: true, class: "search-form")%>
            <%= submit_tag("Search", id: "search_by_surname", class: "btn btn-outline-warning btn-sm search-btn-margin")%>
          <% end %>
        <p>search by birthdate</p>
          <%= form_tag(tribe_members_path, method: :get) do %>
            <%= date_select("member_birthdate", "birthdate", start_year: 1500, end_year: Date.current.year, order: [:year, :month, :day]) %>
            <%= submit_tag("Search", id: "search_by_birthdate", class: "btn btn-outline-warning btn-sm search-btn-margin")%>
          <% end %>
        <p>search by ancestor</p>
          <%= form_tag(tribe_members_path, method: :get) do %>
            <%= text_field_tag(:ancestor_name, params[:ancestor_name], required: true, class: "search-form")%>
            <%= text_field_tag(:ancestor_surname, params[:ancestor_surname], required: true, class: "search-form") %>
            <%= submit_tag("Search", id: "search_by_ancestor_name", class: "btn btn-outline-warning btn-sm search-btn-margin" )%>
          <% end %>
      </div>
    </div>
    <div class="col-6" id="map" style="width: 600px; height: 357px; border-radius: 3px;"></div>
    <script>
      var map = L.map('map').setView([0, 0], 5);
      $.ajax({
        type: "get",
        url: 'geo.geojson',
        dataType: 'json',
        success: function (response) {

          // Empty Layer Group that will receive the clusters data on the fly.
          var markers = L.geoJSON(null, {
            pointToLayer: createClusterIcon
          }).addTo(map);

          // Update the displayed clusters after user pan / zoom.
          map.on('moveend', update);

          function update() {
            if (!ready) return;
            var bounds = map.getBounds();
            var bbox = [bounds.getWest(), bounds.getSouth(), bounds.getEast(), bounds.getNorth()];
            var zoom = map.getZoom();
            var clusters = index.getClusters(bbox, zoom);
            markers.clearLayers();
            markers.addData(clusters);
          }

          // Zoom to expand the cluster clicked by user.
          markers.on('click', function(e) {
            var clusterId = e.layer.feature.properties.cluster_id;
            var center = e.latlng;
            var expansionZoom;
            if (clusterId) {
              expansionZoom = index.getClusterExpansionZoom(clusterId);
              map.flyTo(center, expansionZoom);
            }
          });
          var geojson = response
          var index;
          var ready = false;


          // Initialize the supercluster index.
          index = supercluster({
            radius: 60,
            extent: 256,
            maxZoom: 18
          }).load(geojson.features); // Expects an array of Features.

          ready = true;
          update();





          function createClusterIcon(feature, latlng) {
            if (!feature.properties.cluster) return L.marker(latlng);

            var count = feature.properties.point_count;
            var size =
              count < 100 ? 'small' :
              count < 1000 ? 'medium' : 'large';
            var icon = L.divIcon({
              html: '<div><span>' + feature.properties.point_count_abbreviated + '</span></div>',
              className: 'marker-cluster marker-cluster-' + size,
              iconSize: L.point(40, 40)
            });

            return L.marker(latlng, {
              icon: icon
            });
          }
            }
      });


      L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
      }).addTo(map);
    </script>
  </div>
  <br>
  <div class="row">
    <div class="col-6 offset-3">
        <div class="row">
          <div class="col-5 offset-2">
            <%= link_to "Add a new member", new_tribe_member_path , class: "btn btn-warning"%>
          </div>
          <div class="col-4">
            <%= link_to "See the stats", tribe_members_show_stats_path , class: "btn btn-warning"%>
          </div>
        </div>
      </div>
    </div>

  <br>
  <div class="row">
    <div class="col-12">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Surname</th>
            <th scope="col">Birthdate</th>
            <th scope="col"></th>
            <th scope="col">Ancestor: </th>
            <th scope="col">Id</th>
            <th scope="col">Name </th>
            <th scope="col"> Surname</th>
          </tr>
        </thead>
        <tbody>
          <% if @search_result == "no result" %>
          <p> No Result for this research</p>
          <% elsif @search_result.present? %>
            <% @search_result.each do |tm| %>
              <tr>
                <td><%= tm.name %></td>
                <td><%= tm.surname %></td>
                <td><%= tm.birthdate %></td>
                <td></td>
                <% if tm.ancestor.present? %>
                  <td><%= tm.ancestor.id %></td>
                  <td><%= tm.ancestor.name %></td>
                  <td><%= tm.ancestor.surname %></td>
                <% end %>
              </tr>
            <% end %>

          <% else %>
            <% @tribe_m.each do |tm| %>
              <tr>
                <td><%= tm.name %></td>
                <td><%= tm.surname %></td>
                <td><%= tm.birthdate %></td>
                <td></td>
                <th scope="row">-</th>
                <% if tm.ancestor.present? %>
                  <td><%= tm.ancestor.id %></td>
                  <td><%= tm.ancestor.name %></td>
                  <td><%= tm.ancestor.surname %></td>
                <% end %>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
      <div class="row">
        <% if @search_result.present? %>
          <div class="col-6 offset-5">
            <%= link_to 'See all list', tribe_members_path, class: "btn btn-warning"%>
          </div>
        <% else %>
          <div class="col-6 offset-3">
            <%= will_paginate @tribe_m, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/tribe_members/new.html.erb
<div class="banner">
  <h2>Add a new member !</h2>
</div>
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-6 offset-3">
      <div class="card">
        <%= form_for @tribe_member, url: tribe_members_path(@tribe_member) do |f| %>
          <div class="row">
            <div class="col-6 space-top">
              <%= f.label "Name" %>
            </div>
            <div class="col-6 space-top">
              <%= f.label "surname" %>
            </div>
            <div class="col-6">
              <%= f.text_field :name, required: true%>
            </div>
            <div class="col-6">
              <%= f.text_field :surname, required: true%>
            </div>
            <div class="col-9 space-top">
              <%= f.label :birthdate %>


              <%= f.date_select :birthdate, start_year: 1500, end_year: Date.current.year, order: [:year, :month, :day]%>
            </div>
            <div class="col-6 space-top">
              <%= f.label "Latitude" %>
            </div>
            <div class="col-5 offset-1 space-top">
              <%= f.label "longitude" %>
            </div>
            <div class="col-6 space-top">
              <%= f.text_field :latitude , required: true%>
            </div>
            <div class="col-5 offset-1 space-top">
              <%= f.text_field :longitude , required: true%>
            </div>

            <div class="col-6 space-top">
              <%= f.label :ancestor_name %>
              <%= f.text_field :ancestor_name, required: true %>
            </div>
            <div class="col-5 offset-1 space-top">
              <%= f.label :ancestor_surname %>
              <%= f.text_field :ancestor_surname, required: true %>
            </div>
            <div class="col-5 space-top">
              <%= f.submit "Create member", class: "btn btn-warning btn-custom"%>
            </div>
            <div class="col-5 offset-2 space-top">
              <%= link_to "Back", tribe_members_path, class: "btn btn-warning btn-custom"%>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tribe_members/show_stats.html.erb
<div class="banner">
  <h2>Stats for your tribe</h2>
</div>
<br>
<br>
<div class="container">
  <div class="row">
    <div class="col-6 offset-3">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Total member</th>
            <th scope="col">Average age</th>
            <th scope="col">The oldest member</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @stats[:count] %></td>
            <td><%= @stats[:average]%></td>
            <td><%= @stats[:oldest_member].name + ", " + @stats[:oldest_member].surname + ", age: " + @stats[:age_oldest_member].to_s%></p>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-12">
      <%= line_chart @data_graph, points: false, id: "users-chart", width: "1050px", height: "500px", colors: ["#FFC107", "#FFC107"], xtitle: "Year", ytitle: "Birth"  %>
    </div>

    <div class="col-6 offset-5">
      <%= link_to "Back", tribe_members_path, class: "btn btn-warning btn-custom"%>
    </div>

  </div>
</div>